project_id = "xgsxnnxjyqpyirqwkmix"

[functions.fetch-url-file]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.extract-website-colors]
verify_jwt = false

[functions.scan-image-text]
verify_jwt = false

[functions.scan-url-probe]
verify_jwt = false
